build:
	go build -ldflags "-X github.com/pconcepcion/dice/cmd.BuildDate=`date -u '+%Y-%m-%d_%I:%M:%S%p'` -X github.com/pconcepcion/dice/cmd.CommitHash=`git rev-parse HEAD`" -o dice ./cmd/main.go

install:
	go install

test:
	go test -v -race ./...

gofmt:
	go fmt ./...

lint:
	go vet ./...
	find . -name '*.go' | xargs grep -L '// Code generated by "stringer -type='| xargs golint
	#gocyclo -over 10 .
	errcheck ./...

clean:
	go clean

deps: dev-deps

dev-deps:
	# go get github.com/golang/lint/golint
	go get -u golang.org/x/lint/golint
	go get github.com/kisielk/errcheck
