DigitExcludingZero ::= [1-9]
RightParenthesis ::=")"
LeftParenthesis ::="("
Digit ::= [0-9]
Dice ::= "d"
Explode ::= "e"
Keep ::= "k"
KeepLower ::= "kl"
Open ::= "o"
Reroll ::= "r"
Success ::= "s"
ExplodingSuccess ::= "es"
Natural  ::= DigitExcludingZero Digit*
NaturalPlusZero ::= "0" | Natural
Modifier ::=  Keep NaturalPlusZero |  KeepLower NaturalPlusZero | Explode Natural? | ExplodingSuccess NaturalPlusZero | Open | Reroll  Natural| Success NaturalPlusZero
NumDices ::= Natural
NumSides ::= Natural
Constant ::= NaturalPlusZero
BasicDiceExpression ::= (NumDices? Dice NumSides Modifier?)|Constant
ExpressionOperators ::=  [-*/+]
DiceExpressiion ::= BasicDiceExpression (ExpressionOperators BasicDiceExpression)*| LeftParenthesis DiceExpression RightParenthesis
