DigitExcludingZero ::= [1-9]
Digit ::= [0-9]
Dice ::= "d"
Explode ::= "e"
Keep ::= "k"
KeepLower ::= "kl"
Open ::= "o"
Reroll ::= "r"
Success ::= "s"
ExplodingSuccess ::= "es"
Natural  ::= DigitExcludingZero Digit*
Modifier ::=  Keep Natural |  KeepLower Natural | Explode Natural?  | ExplodingSuccess Natural | Open | Reroll  Natural| Success Natural
NumDices ::= Natural
NumSides ::= Natural
Constant ::= Natural
BasicDiceExpression ::= (NumDices? Dice NumSides Modifier?)|Constant
ExpressionOperators ::=  [-*/+]
DiceExpressiion ::= BasicDiceExpression (ExpressionOperators BasicDiceExpression)*

